In [0]:
#In the Section we are trying to classify the digits which are in multiclass and apply data preprcessing steps 
#Build a model and finding its accuracy   

import pandas as pd
import numpy as np
from sklearn.datasets import *
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

data = load_digits() #Multiclass classification problem

In [2]:
X = data.data
print(X.shape)
print(X)

(1797, 64)
[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [3]:
y =data.target
print(y.shape)
print(y)
print(np.unique(y)) #TO print the no. of unique classes

(1797,)
[0 1 2 ... 8 9 8]
[0 1 2 3 4 5 6 7 8 9]


In [0]:
from sklearn.linear_model import LogisticRegressionCV
from sklearn.model_selection import train_test_split
from sklearn.multiclass import OneVsRestClassifier


In [0]:
#splitting the data in to train and test in 70:30 ratio
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3) 

#Standariziing the dataset values and fitting the X_train values
scalar=StandardScaler().fit(X_train)

#Transforming the X_train and X_test calues 
X_train=scalar.transform(X_train)
X_test=scalar.transform(X_test)

In [0]:
from warnings import filterwarnings
filterwarnings('ignore')

#Creating Losgisitc regression model with Crossvalidation of 5 using the and find the best fit
clr = LogisticRegressionCV(multi_class='multinomial',cv=5).fit(X_train, y_train)

In [7]:
clr.Cs #Best C value

10

In [8]:
print(clr.score)

<bound method LogisticRegressionCV.score of LogisticRegressionCV(Cs=10, class_weight=None, cv=5, dual=False,
                     fit_intercept=True, intercept_scaling=1.0, l1_ratios=None,
                     max_iter=100, multi_class='multinomial', n_jobs=None,
                     penalty='l2', random_state=None, refit=True, scoring=None,
                     solver='lbfgs', tol=0.0001, verbose=0)>


In [0]:
#Predicting the class labels
y_pre = clr.predict(X_test)   #Predicting the labels
y_pre_prob = clr.predict_proba(X_test) # Predicting the class probabilities

In [10]:
acc = accuracy_score(y_test, y_pre)
print(acc)

0.9518518518518518


Summary:

We have analysed the digits dataset available at Scikitlearn.

At first step we have load the data to X and labels to Y.

Second set we have splitted the data in Xtrain, X-test, y_train and y-test
we have standarized the values of data (Xtrain and X-test)
we didn't performed any preprocessin steps due to dataset is available in 
integer form and ther are no missing values

we have performed Logisitc regressio with crossvalidation
we have found out optimum C value of 1 

we have found the accuracy of the model is >95% at the end od testing

In [0]:
#Saving the model in file
import pickle

fle = open('Log_reg_digits_model.sav', 'wb')
pickle.dump(clr, fle)

#Loading the model from the file
model = pickle.load(open('Log_reg_digits_model.sav', 'rb'))